// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6QObgX4QLoHgzbkEPzAbI9fuW2yTDBvc',
    appId: '1:628291638018:web:7cba7d7965d1075ef4281b',
    messagingSenderId: '628291638018',
    projectId: 'fir-app-31db5',
    authDomain: 'fir-app-31db5.firebaseapp.com',
    storageBucket: 'fir-app-31db5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGeDJTPonFkV_VxxjqbwzxciZoQDq0aPI',
    appId: '1:628291638018:android:9aa9a76fe759b8aef4281b',
    messagingSenderId: '628291638018',
    projectId: 'fir-app-31db5',
    storageBucket: 'fir-app-31db5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrZ9D5cofbh6UeTJXzqIaiRpsIh7Mw3ZA',
    appId: '1:628291638018:ios:16f141b74a807ac6f4281b',
    messagingSenderId: '628291638018',
    projectId: 'fir-app-31db5',
    storageBucket: 'fir-app-31db5.appspot.com',
    iosClientId: '628291638018-4len4v0g4scb4u5oub9eevblpev72r2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrZ9D5cofbh6UeTJXzqIaiRpsIh7Mw3ZA',
    appId: '1:628291638018:ios:16f141b74a807ac6f4281b',
    messagingSenderId: '628291638018',
    projectId: 'fir-app-31db5',
    storageBucket: 'fir-app-31db5.appspot.com',
    iosClientId: '628291638018-4len4v0g4scb4u5oub9eevblpev72r2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
